#build
apiVersion: "v1"
kind : "BuildConfig"
metadata:
  name: "custom-jenkins"
spec:
  source:
    git:
      uri: "https://github.com/DerBrecher/custom-jenkins"
#    sourceSecret:
#      name: openshift secret name
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      type: Docker
  output:
    to:
      kind: "ImageStreamTag"
      name: "custom-jenkins:latest"