#build
kind : "BuildConfig"

apiVersion: "v1"
metadata:
  name: "custom-jenkins"
spec:
  source:
    git:
      uri: "https://github.com/DerBrecher/custom-jenkins"
  strategy:
    type: Docker
    dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "custom-jenkins"